services:
  wordpress:
    image: "wordpress:latest"
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - ./:/var/www/html/wp-content/plugins/allergens-dietary-ictoria
      - wp-plugins:/var/www/html/wp-content/plugins
      - ./debug:/var/www/html/wp-content/logs
      - ./tests:/var/www/html/wordpress-tests
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini
    networks:
      development:
        ipv4_address: "124.168.92.20"

  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      development:
        ipv4_address: "124.168.92.21"
  phpmyadmin:
    image: "phpmyadmin:latest"
    ports:
      - "8181:80"
    depends_on:
      - mysql
    environment:
      PMA_PORT: 3306
      PMA_HOST: mysql
    networks:
      development:
        ipv4_address: "124.168.92.22"
  # phpunit:
  #   image: "wordpressdevelop/phpunit"
  #   depends_on:
  #     - wordpress
  #     - mysql
  #   networks:
  #     - development

  phpunit:
    build: 
      context: .
      dockerfile: phpunit/Dockerfile
    volumes:
      - ./:/var/www/html/wp-content/plugins/allergens-dietary-ictoria
      - ./tests:/var/www/html/wordpress-tests
    depends_on:
      - wordpress
      - mysql
    entrypoint: ["/bin/sh", "-c", "/var/www/html/wordpress-tests/bin/install-wp-tests.sh wordpress root '' mysql && vendor/bin/phpunit"]
    networks:
      development:

volumes:
  wp-plugins:

networks:
  development:
    ipam:
      driver: default
      config:
        - subnet: "124.168.92.0/24"
