services:
  wordpresslatest:
    image: "wordpress:latest"
    # pull_policy: "always"
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
        restart: true
        required: true
      phpmyadmin:
        condition: service_started
        required: true
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: true
      WORDPRESS_DEBUG_LOG: true
    volumes:
      - ./allergens-dietary-pro:/var/www/html/wp-content/plugins/allergens-dietary-pro
      - ${FREE_PATH}:/var/www/html/wp-content/plugins/allergens-dietary
      - ./debug:/var/www/html/wp-content/logs
      - ./phpunit/tests:/var/www/html/wordpress-tests/
      # - ./wordpress:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini
    networks:
      development:
        ipv4_address: "124.168.92.20"

  wordpressminus1:
    image: "wordpress:6.6.1"
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_NAME: wordpress
    networks:
      development:
        ipv4_address: "124.168.92.18"

  wordpressminus2:
    image: "wordpress:6.5.5"
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./allergens-dietary-pro:/var/www/html/wp-content/plugins/allergens-dietary-pro
    networks:
      development:
        ipv4_address: "124.168.92.19"

  db:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      development:
        ipv4_address: "124.168.92.21"

  phpmyadmin:
    image: "phpmyadmin:latest"
    ports:
      - "8181:80"
    depends_on:
      - db
    environment:
      PMA_PORT: 3306
      PMA_HOST: db
    networks:
      development:
        ipv4_address: "124.168.92.22"

  phpunit:
    build:
      context: .
      dockerfile: phpunit/Dockerfile
    volumes:
      - ./allergens-dietary-pro:/var/www/html/wp-content/plugins/allergens-dietary-pro
      - ./phpunit/tests:/var/www/html/wordpress-tests/
      # - ./wordpress:/var/www/html/
    depends_on:
      - wordpresslatest
    networks:
      development:

  yippee:
    image: "mysql:latest"
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: wp-allergenen-pro
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      allergenKey:
        ipv4_address: "126.168.94.21"

  yipie-admin:
    image: "phpmyadmin:latest"
    ports:
      - "8181:80"
    depends_on:
      - yippee
    environment:
      PMA_PORT: 3306
      PMA_HOST: yippee
    networks:
      allergenKey:
        ipv4_address: "126.168.94.22"

networks:
  development:
    ipam:
      driver: default
      config:
        - subnet: "124.168.92.0/24"
  allergenKey:
    ipam:
      driver: default
      config:
        - subnet: "126.168.94.0/24"
