<?php
//exit if user can access this file directly
if(!defined('ABSPATH')){
	exit;
}

//class that contains functions that are used by multiple classes/files or do not belong in another class
class Allergens_Dietary_Ictoria_Functions{
	
	//function to get a translation of all text contained within __() functions throughout the plugin IF the .mo and .po files for the local/server language are available
	public static function load_textdomain(){
		load_plugin_textdomain('allergens-dietary-ictoria', false, basename(ALLERGENS_DIETARY_ICTORIA_FILE).'/l10n'); 
	}
	
	//Get all relevant plugin settings from the WP options table
	public static function get_settings(){
		return get_option('allergens_dietary_ictoria_settings');
	}
	
	//Get all allergens and dietary options added by this plugin from the WP options table
	public static function get_options(){
		return get_option('allergens_dietary_ictoria_options');
	}
	
	// //adds the external css file(s) to the current WP execution
	// public static function load_style(){
	// 	wp_register_style('allergens-dietary-ictoria-css', plugins_url(ALLERGENS_DIETARY_ICTORIA_NAME.'/assets/css/allergens-dietary-ictoria.css'));
  //   	wp_enqueue_style('allergens-dietary-ictoria-css');
	// }
	
	// //adds the external js file(s) to the current WP execution
	// public static function load_admin_js(){
	// 	wp_register_style('allergens-dietary-ictoria-css', plugins_url(ALLERGENS_DIETARY_ICTORIA_NAME.'/assets/css/allergens-dietary-ictoria.css'));
  //   	wp_enqueue_style('allergens-dietary-ictoria-css');
	// 	wp_register_script('allergens-dietary-admin-js', plugins_url(ALLERGENS_DIETARY_ICTORIA_NAME.'/assets/js/admin_set_options_by_category.js'), array('jquery'));
	// 	wp_enqueue_script( 'allergens-dietary-admin-js');
	// }
	
	//adds the external css file(s) to the current WP execution
  public static function load_style() {
    add_action('wp_enqueue_scripts', [__CLASS__, 'enqueue_styles']);
    add_action('admin_enqueue_scripts', [__CLASS__, 'enqueue_admin_styles']);
  }
 
  public static function enqueue_styles() {
    wp_enqueue_style('allergens-dietary-ictoria-css', plugins_url('assets/css/allergens-dietary-ictoria.css', ALLERGENS_DIETARY_ICTORIA_FILE));
  }
 
  public static function enqueue_admin_styles() {
    // wp_enqueue_style('allergens-dietary-ictoria-admin-css', plugins_url('assets/css/allergens-dietary-ictoria-admin.css', ALLERGENS_DIETARY_ICTORIA_FILE));
    wp_enqueue_style('allergens-dietary-ictoria-admin-css', plugins_url('assets/css/allergens-dietary-ictoria.css', ALLERGENS_DIETARY_ICTORIA_FILE));
  }
 
  // Enqueue admin JS script
  public static function load_admin_js() {
    add_action('admin_enqueue_scripts', [__CLASS__, 'enqueue_admin_scripts']);
  }
 
  public static function enqueue_admin_scripts() {
      wp_enqueue_script(
          'allergens-dietary-admin-js',
          plugins_url('assets/js/admin_set_options_by_category.js', ALLERGENS_DIETARY_ICTORIA_FILE),
          ['jquery'],
          false,
          true
      );
  }

	//function that handles error notices of this plugin. Every error notice generated by this plugin will call this function, sending both the notice level(WP css class) and the(translated) message
	public static function error_notice($level, $message){
		$message_header = sprintf(__('%1$sAllergens and Dietary is inactive:%2$s', 'allergens-dietary-ictoria'), '<p><strong>', '</strong></p>');
		$message_full = $message_header.$message;
		add_action(
			'admin_notices',
			static function () use ($level, $message_full){
				echo '<div class="notice '.esc_attr($level).'" style="padding:12px 12px">
					'.wp_kses_post($message_full).'
				</div>';
			}
		);
	}
	
	//return an array containing all allergens and dietary options that this plugin adds
	public static function default_options(){
		//Every option has a category, title, status, filter-action, filter-extra and icon
		//status is used to enable/disable an option globally
		//filter-action is used to tell the filter if products with the selected option should be included or excluded
		//filter-extra is used to add extra text in front of the option in the filter menu
		$no = __('no ', 'allergens-dietary-ictoria');
		$options = array(
			'peanuts' => array(
				'category' => 'allergen',
				'title' => __('Peanuts', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon'  => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_peanuts.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'nuts' => array(
				'category' => 'allergen',
				'title' => __('Nuts', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon'  => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_nuts.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'sesame' => array(
				'category' => 'allergen',
				'title' => __('Sesame', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon'  => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_sesame.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'lupin' => array(
				'category' => 'allergen',
				'title' => __('Lupin', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon' => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_lupin.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'soya' => array(
				'category' => 'allergen',
				'title' => __('Soya', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon'  => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_soya.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'mustard' => array(
				'category' => 'allergen',
				'title' => __('Mustard', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon'  => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_mustard.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'eggs' => array(
				'category' => 'allergen',
				'title' => __('Eggs', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon'  => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_eggs.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'dairy' => array(
				'category' => 'allergen',
				'title' => __('Dairy', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon'  => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_dairy.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'fish' => array(
				'category' => 'allergen',
				'title' => __('Fish', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon'  => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_fish.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'crustaceans' => array(
				'category' => 'allergen',
				'title' => __('Crustaceans', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon'  => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_crustaceans.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'molluscs' => array(
				'category' => 'allergen',
				'title' => __('Molluscs', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon'  => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_molluscs.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'gluten' => array(
				'category' => 'allergen',
				'title' => __('Gluten', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon'  => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_gluten.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'corn' => array(
				'category' => 'allergen',
				'title' => __('Corn', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon'  => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_corn.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'wheat' => array(
				'category' => 'allergen',
				'title' => __('Wheat', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon'  => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_wheat.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'celery' => array(
				'category' => 'allergen',
				'title' => __('Celery', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon'  => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_celery.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'sulfite' => array(
				'category' => 'allergen',
				'title' => __('Sulfite', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon' => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_sulfite.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'alcohol' => array(
				'category' => 'allergen',
				'title' => __('Alcohol', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => $no,
				'icon' => plugins_url('allergens-dietary-ictoria/assets/icons/allergens_alcohol.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'vegetarian' => array(
				'category' => 'dietary',
				'title' => __('Vegetarian', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'include',
				'filter-extra' => '',
				'icon' => plugins_url('allergens-dietary-ictoria/assets/icons/dietary_vegetarian.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'vegan' => array(
				'category' => 'dietary',
				'title' => __('Vegan', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'include',
				'filter-extra' => '',
				'icon' => plugins_url('allergens-dietary-ictoria/assets/icons/dietary_vegan.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'halal' => array(
				'category' => 'dietary',
				'title' => __('Halal', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'include',
				'filter-extra' => '',
				'icon' => plugins_url('allergens-dietary-ictoria/assets/icons/dietary_halal.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			),
			'pregnant' => array(
				'category' => 'dietary',
				'title' => __('Risk for pregnant women', 'allergens-dietary-ictoria'),
				'status' => 'active',
				'filter-action' => 'exclude',
				'filter-extra' => '',                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   '',
				'icon' => plugins_url('allergens-dietary-ictoria/assets/icons/dietary_pregnant.png', ALLERGENS_DIETARY_ICTORIA_DIRNAME)
			)
		);
		return $options;
	}
}
?>