<?php
// exit if user can access this file directly
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * @author V.B.
 * @covers Allergens_Dietary_Ictoria_Functions
 * @important
 * This class will be outdated when the plugin
 * does not include anything anymore from the functions.php file.
 * this is also part of the planning in the future.
 */

class Allergens_Dietary_Ictoria_Functions {

	// function to get a translation of all text contained within __() functions throughout the plugin IF the .mo and .po files for the local/server language are available
	public static function load_textdomain() {
		load_plugin_textdomain( __( 'allergens-dietary-ictoria', 'allergens-dietary-ictoria' ), false, basename( ALLERGENS_DIETARY_ICTORIA_FILE ) . '/l10n' );
	}

	// Get all relevant plugin settings from the WP options table
	public static function get_settings() {
		return get_option( __( 'allergens_dietary_ictoria_settings', 'allergens-dietary-ictoria' ) );
	}
	
	//Get all allergens and dietary options added by this plugin from the WP options table
	public static function get_options(){
		return get_option( __( 'allergens_dietary_ictoria_options', 'allergens-dietary-ictoria' ));
	}

	// //adds the external css file(s) to the current WP execution
	// public static function load_style(){
	// wp_register_style('allergens-dietary-ictoria-css', plugins_url(ALLERGENS_DIETARY_ICTORIA_NAME.'/assets/css/allergens-dietary-ictoria.css'));
	// wp_enqueue_style('allergens-dietary-ictoria-css');
	// }

	// //adds the external js file(s) to the current WP execution
	// public static function load_admin_js(){
	// wp_register_style('allergens-dietary-ictoria-css', plugins_url(ALLERGENS_DIETARY_ICTORIA_NAME.'/assets/css/allergens-dietary-ictoria.css'));
	// wp_enqueue_style('allergens-dietary-ictoria-css');
	// wp_register_script('allergens-dietary-admin-js', plugins_url(ALLERGENS_DIETARY_ICTORIA_NAME.'/assets/js/admin_set_options_by_category.js'), array('jquery'));
	// wp_enqueue_script( 'allergens-dietary-admin-js');
	// }

	// adds the external css file(s) to the current WP execution
	public static function load_style() {
		add_action( 'wp_enqueue_scripts', array( __CLASS__, 'enqueue_styles' ) );
		add_action( 'admin_enqueue_scripts', array( __CLASS__, 'enqueue_admin_styles' ) );
	}

	public static function enqueue_styles() {
		wp_enqueue_style( 'allergens-dietary-ictoria-css', plugins_url( 'assets/css/allergens-dietary-ictoria.css', ALLERGENS_DIETARY_ICTORIA_FILE ) );
	}

	public static function enqueue_admin_styles() {
		// wp_enqueue_style('allergens-dietary-ictoria-admin-css', plugins_url('assets/css/allergens-dietary-ictoria-admin.css', ALLERGENS_DIETARY_ICTORIA_FILE));
		wp_enqueue_style( 'allergens-dietary-ictoria-admin-css', plugins_url( 'assets/css/allergens-dietary-ictoria.css', ALLERGENS_DIETARY_ICTORIA_FILE ) );
	}

	// Enqueue admin JS script
	public static function load_admin_js() {
		add_action( 'admin_enqueue_scripts', array( __CLASS__, 'enqueue_admin_scripts' ) );
	}

	public static function enqueue_admin_scripts() {
		wp_enqueue_script(
			'allergens-dietary-admin-js',
			plugins_url( 'assets/js/admin_set_options_by_category.js', ALLERGENS_DIETARY_ICTORIA_FILE ),
			array( 'jquery' ),
			false,
			true
		);
	}

	// function that handles error notices of this plugin. Every error notice generated by this plugin will call this function, sending both the notice level(WP css class) and the(translated) message
	public static function error_notice( $level, $message ) {
		$message_header = sprintf( __( '%1$sAllergens and Dietary is inactive:%2$s', 'allergens-dietary-ictoria' ), '<p><strong>', '</strong></p>' );
		$message_full   = $message_header . $message;
		add_action(
			'admin_notices',
			static function () use ( $level, $message_full ) {
				echo '<div class="notice ' . esc_attr( $level ) . '" style="padding:12px 12px">
					' . wp_kses_post( $message_full ) . '
				</div>';
			}
		);
	}

	public function upload_language_file() {
		$language_path          = WP_LANG_DIR . '/plugins';
		$language_file_basename = 'allergens-dietary-ictoria';
		$user_locale            = get_user_locale();
		$files_templates        = array(
			'.po', // Default template for all locales.
			'.mo',
		);

		foreach ( $files_templates as $files_template ) {
			$language_file_fullname = $language_file_basename . $user_locale . $files_template;
			$plugin_language_file   = ALLERGENS_DIETARY_ICTORIA . '/languages/' . $language_file_fullname;

			if ( file_exists( $plugin_language_file ) && $language_path . '/' . $language_file_fullname ) {

				copy( $plugin_language_file, $language_path . '/' . $language_file_fullname );
			}
		}
	}
}
