@startuml Allergens_Dietary_Ictoria_Filter

class Allergens_Dietary_Ictoria_Filter {
    -{static} _instance : Allergens_Dietary_Ictoria_Filter
    +{static} instance() : Allergens_Dietary_Ictoria_Filter
    ..
    +create_filter() : void
    +filter_query($query) : void
}

class Allergens_Dietary_Ictoria_Functions {
    +{static} get_options() : array
}

' interface WordPress_Plugin_API {
'     +add_action(hook, callback)
'     +add_filter(hook, callback)
' }

Allergens_Dietary_Ictoria_Filter --> Allergens_Dietary_Ictoria_Functions : uses

@enduml
