@startuml classdiagram
skinparam Linetype ortho
skinparam groupInheritance 2

note as N1
In this diagram we are showing the classes and their methods that are used in the Allergens Dietary Ictoria plugin.
and not any WordPress core classes or methods.
Likewise with Woocommerce.
end note

note as N2
The file called Allergens_Dietary_Pro is the main file for the plugin.
But contains 2 classes these must be separated in a later rendition of the plugin.
This to support the Single Responsibility Principle and maintain clean code.
end note

note as N3
All classes that do not have a relation are pure singleton classes.
Meaning there can only be one instance of the object at any given time.
end note

package "php"{

    class Allergens_Dietary_Pro_Plugin_Menu{
        + addMyAdminMenu() : void
        + addallergens() : void
        + updateallergens() : void
        + licenseForm() : void
        + showallergens() : void
        + info() : void
    }

    package "tables"{
         class Allergens_Dietary_Pro_Show_Allergens{
            # __construct() : void
            # get_bulk_actions() : array
            # column_allergy_name(item:array|object) : string
            # process_bulk_action() : void
            # handle_row_actions(item:array|object, column_name:string, primary:string) : void
        }
    }
    package "notice"{

        enum NoticeTypes{
            ERROR
            INFO
            SUCCESS
            NOTICE
        }

        class Allergens_Dietary_Pro_Notices{
            # __construct():void 
            + error_notice(type:NoticeType, message:string) : void
        }

    }

    package "forms"{

        interface I_Allergens_Dietary_Pro_Form{
            + showForm(allergenName:String) : void
            + submit(data:array) : void
            + sanitize(data:array) : array
        }

        class Allergens_Dietary_Pro_Form{
            - __construct() : void
            + showForm(allergenName:String) : void
        }

        class Allergens_Dietary_Pro_Allergens_Form{
            - _allergen : array
            - MIME_TYPES : array
            - MIME_NAMES : array
            - {static} _message : string 
            - {static} _type: Notice_Types
            + __construct(): void
            + showForm(allergenName:String) : void
            + submit(data:array) : void
            # handle_redirect(data:array, return_to_page:bool, editin:bool, skip:bool)
            # valid_input(data:array, editing:bool, all_query:object, att_query:object, valid_icon:bool, empty_file_input:bool) :bool
            # handle_edit(data:array, all_query:object, att_query:object, all_att_query:object, empty_file_input:bool):void
            # handle_add(data:array, all_query:object, att_query:object, all_att_query:object, empty_file_input:bool, no_icon_selected:bool): void
            + sanitize(data:array) : array
            - do_dropdown() : string
        }

        class Allergens_Dietary_Pro_License_Form{
            + __construct(): void
            + showForm(allergenName:String) : void
            + submit(data:array) : void
            + sanitize(data:array) : array
        }
        class Allergens_Dietary_Pro_Update_Allergen_Form{
            - MIME_TYPES : array
            - MIME_NAMES : array
            - _allergens: array
            - {static} _message: string
            + __construct() : void
            + showForm(allergenName:string) : void
            + submit(data:array) : void
            + sanitize(data:array) : array
            - replace_spaces(allergen:string) : string
        }
    }

    package "DB" {
        class Allergens_Dietary_Pro_Allergen_Queries{
            -{static} instances : array
            +{static} getInstance() : self
            # __construct() : void
            + getAllAllergens() : array
            + {static} includeItems() : void
            + is_default_allergen(allergy_name:string) : boolean
            + {static} getItems() : array
            + {static} getColumns() : array
            + activationUpdate(data:array) : void
            + singleActivationUpdate() : void
            + addAllergens(data:array) : boolean
            + checkAllergenExists(allergenName:string) : boolean
            + updateAllergens(data:array) : void
            + getAllergen(allergenName:string) : array
            + {static} delete_allergen_by_name(allergy_name:string) : void
        }

        class Allergens_Dietary_Pro_Attachment_Queries{
            -{static} instances : array
            +{static} getInstance() : self
            - path : string
            - _url : string
            # __construct() : void
            + {static} attachment_insert(result:array) : void
            + addAttachment(data:array) : boolean
            + deleteAttachment(attachment:string) : void
            + checkAttachmentExists(attachmentName:string) : boolean
            + updateAttachment(data:array, oldName:string) : void
            - placeAttachment(data:array) : void
            - removeAttachment(attachmentName: string) : void
        }

        class Allergens_Dietary_Pro_Allergy_Attachment_Queries{
            -{static} instances : array
            +{static} getInstance() : self
            # __construct() : void
            + getAllergyAttachment(allergyAttachmentName:string, isForm:boolean) : array
            + getAllAllergyAttachmments(skip_default:boolean) : array
            + {static} allergy_connection(result:array) : array
            + addAllergyAttachment(data:array) : boolean
            + updateAllergyAttachment(data:array) : void
            + attachmentIsUsed() : boolean
            + checkAllergyAttachmentExists(allergy_name:string) : boolean
            + deleteAllergyAttachment(allergy:string) : void
            + checkMultipleAttachmentsExists(icon:string, bool:boolean) : boolean
        }
        class Allergens_Dietary_Pro_Allergy_Product_Queries{
            -{static} instances : array
            +{static} getInstance() : self
            # __construct() : void
            + addAllergyProduct(product_id:int, allergen:string) : boolean
            + getAllergyProduct(product_id:int, allergen:string=null) : array
            + deleteAllergyProduct(product_id:int, allergen:String) : boolean
            + getFilteredProducts(allergens:array, dietary:array)
        }
    }
    package "lists" {
        class Allergens_Dietary_Pro_Info{
            + showinfo() : void
            + {static} getInstance() : Allergens_Dietary_Pro_Info
            + {static} getStyles() : void
        }
        enum Mime_Types{
            + get_mime_types() : array
        }
        
        enum FormType{
            ALLERGENS
            LICENSE
            UPDATE

            + match(formType:FormType) : boolean
        }
    }

    package "tabs" {
        class Allergens_Dietary_Pro_Tabs{
            + showtabs() : void
            + showpages() : void
            + {static} getInstance() : Allergens_Dietary_Pro_Tabs
            + {static} getStyles() : void

        }
    }  
}

package Allergens_Dietary_Pro{
    class Allergens_Dietary_Pro_Load_Language{
        + __construct() : void
        + translation_init() : void
    }
    class Allergens_Dietary_Pro_Startup{
        +{static} on_activation : void
        +{static} on_deactivation : void
    }
    class Allergens_Dietary_Pro_Wc_Integration_Startup{
        +init_integration() : void
        +add_integration(integrations:array) : array
    }
}


N2 -- Allergens_Dietary_Pro
Allergens_Dietary_Pro +-u- php

Allergens_Dietary_Pro_Products ..> Allergens_Dietary_Pro_Allergy_Product_Queries


' forms relations
FormType  <.. Allergens_Dietary_Pro_Form 
Allergens_Dietary_Pro_Form o-r-> I_Allergens_Dietary_Pro_Form
Allergens_Dietary_Pro_License_Form ..|> I_Allergens_Dietary_Pro_Form
Allergens_Dietary_Pro_Allergens_Form .u.|> I_Allergens_Dietary_Pro_Form
Allergens_Dietary_Pro_Allergens_Form ..> Allergens_Dietary_Pro_Tabs : uses
Allergens_Dietary_Pro_Allergens_Form ..> Allergens_Dietary_Pro_Allergen_Queries : uses
Allergens_Dietary_Pro_Allergens_Form .r.> Allergens_Dietary_Pro_Attachment_Queries : uses
Allergens_Dietary_Pro_Allergens_Form ..> Allergens_Dietary_Pro_Allergy_Attachment_Queries : uses
@enduml