@startuml classdiagram
skinparam Linetype ortho
skinparam groupInheritance 2

note as N1
In this diagram we are showing the classes and their methods that are used in the Allergens Dietary Ictoria plugin.
and not any WordPress core classes or methods.
Likewise with Woocommerce.
end note

note as N2
The file called Allergens_Dietary_Ictoria is the main file for the plugin.
But contains 2 classes these must be separated in a later rendition of the plugin.
This to support the Single Responsibility Principle and maintain clean code.
end note

package "php"{

    class Allergens_Dietary_Ictoria_Filter{
        -{static} _instance : Allergens_Dietary_Ictoria_Filter
        +{static} instance() : Allergens_Dietary_Ictoria_Filter
        - __construct() : void
        +create_filter() : void
        +filter_query(query : String) : void
    }

    class Allergens_Dietary_Ictoria_Functions {
        +{static} load_textdomain() : void
        +{static} get_settings() : array
        +{static} get_options() : array
        +{static} load_style() : void
        +{static} enqueue_styles() : void
        +{static} enqueue_admin_styles() : void
        +{static} load_admin_js() : void
        +{static} enqueue_admin_scripts() : void
        +{static} error_notice(level:string, message:string) : void
        + upload_language_file() : void
    }

    class Allergens_Dietary_Ictoria_Activator{
        -{static} counter: int
        -{static} url: string
        -{static} allergens_options: array
        -{static} allergy_icon_options: array
        -{static} icon_options: array
        +{static} activate() : void
        + __construct() : void
        -{static} create_tables() : void
        +{static} initialize() : void
        +{static} allergens_options() : array
        +{static} allergy_icon_options() : array
        +{static} icon_options() : array
        +{static} insert_standard_data() : void
    }

    class Allergens_Dietary_Ictoria_Product_Settings{
        -{static} _instance : Allergens_Dietary_Ictoria_Product_Settings
        + __construct() : void
        + data_tab(product_data_tabs:array) : array
        + data_fields() : void
        + save_product_options(post_id:int) : void
    }

    class Allergens_Dietary_Ictoria_Products{
        -{static} _instance : Allergens_Dietary_Ictoria_Products
        +{static} instance() : Allergens_Dietary_Ictoria_Products
        + __construct() : void
        + show_product_options() : void
        + render_html(data:array): string

    }

    class Allergens_Dietary_Ictoria_Wc_Integration_Settings{
        + __construct() : void
        + init_form_fields() : void
        + generate_allergensdietary_html() : void
        + save_settings(post:array) : void
        +{static} plugin_action_links(links:array) : array
    }
    package "tables"{
         class Allergens_Dietary_Ictoria_Show_Allergens{
            - {static} _instance : Allergens_Dietary_Ictoria_Show_Allergens
            - __construct() : void
            - table_action_options : array
            + get_table_columns_and_data() : array
            + column_default(item:array, column_name:string) : string
            + column_cb(item:array) : string
            + single_row(item:array) : void
            + get_bulk_actions() : array
            # edit_row_action(id:string) : string
            + handle_row_actions(item:array, column_name:string, primary:string) : array
            - build_action_url(action:string, item:array) : string
            # single_row_columns(item:object) : void
            + get_columns() : array
            + prepare_items() : void
            + process_quick_action() : void
            + process_bulk_action(data:array) : void
            + {static} getInstance() : Allergens_Dietary_Ictoria_Show_Allergens
            + table_page() : void
        }
    
}
    package "forms"{

        enum FormType{
            ALLERGENS
            LICENSE

            + match(formType:FormType) : boolean
        }

        interface I_Allergens_Dietary_Ictoria_Form{
            + showForm(allergenName:String) : void
            + submit(data:array) : void
            + sanitize(data:array) : array
        }

        class Allergens_Dietary_Ictoria_Form{
            -{static} _instance : Allergens_Dietary_Ictoria_Allergens_Form
            -{static} formType : FormType
            -{static} formObject : I_Allergens_Dietary_Ictoria_Form
            - __construct() : void
            + {static} getInstance() : Allergens_Dietary_Ictoria_Allergens_Form
            + {static} setFormType(formType:FormType) : void
            + {static} getFormType() : FormType
            + showForm(allergenName:String) : void
        }

        class Allergens_Dietary_Ictoria_Allergens_Form{
            - _allergen : array
            + __construct(): void
            + showForm(allergenName:String) : void
            + submit(data:array) : void
            + sanitize(data:array) : array
            - do_dropdown() : string
        }

        class Allergens_Dietary_Ictoria_License_Form{
            + __construct(): void
            + showForm(allergenName:String) : void
            + submit(data:array) : void
            + sanitize(data:array) : array
        }
    }

    package "DB" {
        class Allergens_Dietary_Ictoria_Allergen_Queries{
            -{static} _instance : Allergens_Dietary_Ictoria_Allergen_Queries
            +{static} getInstance() : Allergens_Dietary_Ictoria_Allergen_Queries
            - __construct() : void
            + addAllergens(data:array) : boolean
            + checkAllergenExists(allergenName:string) : boolean
            + updateAllergens(data:array) : void
            + getAllergen(allergenName:string) : array
            + {static} getItems() : array
            + {static} getColumns() : array
            + {static} includeItems() : void
        }

        class Allergens_Dietary_Ictoria_Attachment_Queries{
            -{static} _instance : Allergens_Dietary_Ictoria_Attachment_Queries
            +{static} getInstance() : Allergens_Dietary_Ictoria_Attachment_Queries
            - __construct() : void
            + addAttachment(data:array) : boolean
            + checkAttachmentExists(attachmentName:string) : boolean
            + updateAttachment(data:array, oldName:string) : void
            - placeAttachment(data:array) : void
            + {static} attachment_insert(result:array) : void
        }

        class Allergens_Dietary_Ictoria_Allergy_Attachment_Queries{
            -{static} _instance : Allergens_Dietary_Ictoria_Allergy_Attachment_Queries
            +{static} getInstance() : Allergens_Dietary_Ictoria_Allergy_Attachment_Queries
            - __construct() : void
            + addAllergyAttachment(data:array) : boolean
            + checkAllergyAttachmentExists(allergyName:string) : boolean
            + find_allergy(allergy_name:string) : string
            + updateAllergyAttachment(data:array) : void
            + getAllergyAttachment(allergyAttachmentName:string) : array
            + {static} allergy_connection(result:array) : array
        }
    }
    package "lists" {
        class Allergens_Dietary_Ictoria_Info{
            + showinfo() : void
            + {static} getInstance() : Allergens_Dietary_Ictoria_Info
            + {static} getStyles() : void
        }
    }
    package "tabs" {
        class Allergens_Dietary_Ictoria_Tabs{
            + showtabs() : void
            + showpages() : void
            +{static} getInstance() : Allergens_Dietary_Ictoria_Tabs
            +{static} getStyles() : void

        }
    }

    
}

package Allergens_Dietary_Ictoria{
    class load_language{
        + __construct() : void
        + translation_init() : void
    }
    class Allergens_Dietary_Ictoria_Startup{
        +{static} on_activation : void
        +{static} on_deactivation : void
    }
    class Allergens_Dietary_Ictoria_Wc_Integration_Startup{
        +init_integration() : void
        +add_integration(integrations:array) : array
    }
}
N2 -- Allergens_Dietary_Ictoria
Allergens_Dietary_Ictoria +-u- php

Allergens_Dietary_Ictoria_Filter --> Allergens_Dietary_Ictoria_Functions : uses
Allergens_Dietary_Ictoria_Wc_Integration_Settings -r-> Allergens_Dietary_Ictoria_Functions : uses
Allergens_Dietary_Ictoria_Product_Settings -l-> Allergens_Dietary_Ictoria_Functions : uses


' forms relations
FormType  <.. Allergens_Dietary_Ictoria_Form 
Allergens_Dietary_Ictoria_Form o-r-> I_Allergens_Dietary_Ictoria_Form
Allergens_Dietary_Ictoria_License_Form ..|> I_Allergens_Dietary_Ictoria_Form
Allergens_Dietary_Ictoria_Allergens_Form .u.|> I_Allergens_Dietary_Ictoria_Form
Allergens_Dietary_Ictoria_Allergens_Form ..> Allergens_Dietary_Ictoria_Tabs : uses
Allergens_Dietary_Ictoria_Allergens_Form ..> Allergens_Dietary_Ictoria_Allergen_Queries : uses
Allergens_Dietary_Ictoria_Allergens_Form .r.> Allergens_Dietary_Ictoria_Attachment_Queries : uses
Allergens_Dietary_Ictoria_Allergens_Form ..> Allergens_Dietary_Ictoria_Allergy_Attachment_Queries : uses
@enduml