<?php

	/**
	 * @brief This class handles the errors.
	 * @author T.K.
	 * @since 1.0.0
	 * @date 4-11-2024
	 */

class Allergens_Dietary_Ictoria_Error_notice {
    	
    // function that handles error notices of this plugin. Every error notice generated by this plugin will call this function, sending both the notice level(WP css class) and the(translated) message
	public static function error_notice( $level, $message ) {
		$message_header = sprintf( __( '%1$sAllergens and Dietary is inactive:%2$s', 'allergens-dietary-ictoria' ), '<p><strong>', '</strong></p>' );
		$message_full   = $message_header . $message;
		add_action(
			'admin_notices',
			static function () use ( $level, $message_full ) {
				echo '<div class="notice ' . esc_attr( $level ) . '" style="padding:12px 12px">
					' . wp_kses_post( $message_full ) . '
				</div>';
			}
		);
	}

}