<?php

if (! defined('ABSPATH')) {
	exit;
}

if (! enum_exists('Notice_Types')) {
	require_once ALLERGENS_DIETARY_PRO_DIRNAME . '/php/notice/notice_Types.php';
}

/**
 * @brief This class handles the errors. 
 * and carries out potential error logs for future development
 * @author Ictoria
 * @since 1.0.0
 * @date 4-11-2024
 */

class Allergens_Dietary_Pro_Notices
{

	private static ?Allergens_Dietary_Pro_Notices $_instance = null;
	
	/**
	 * @brief singleton method to get the instance of the class
	 * @return Allergens_Dietary_Pro_Notices
	 * @author Ictoria
	 * @since 0.17.0.0
	 * @date 18-11-2024
	 */
	public static function getInstance(): Allergens_Dietary_Pro_Notices
	{
		if (is_null(self::$_instance)) {
			self::$_instance = new Allergens_Dietary_Pro_Notices();
		}

		return self::$_instance;
	}

	/**
	 * @brief a private constructor for the class
	 * sets css amongst other things
	 * @author Ictoria
	 * @since 0.17.0.0
	 * @date 18-11-2024
	 */
	private function __construct() {
	}
	/**
	 * @brief method that handles error notices of this plugin. Every error notice generated by this plugin will call this function, sending both the notice type(WP css class) and the(translated) message
	 * @param Notice_Types $type
	 * @param string $message
	 * @return void
	 * @author Ictoria
	 * @since 1.0.0
	 * @date 4-11-2024
	 */
	public function error_notice($type, $message)
	{
		$message_header = sprintf(__('%1$sAllergens and Dietary is inactive:%2$s', 'allergens-dietary-pro'), '<p><strong>', '</strong></p>');
		$message_full   = $message_header . $message;
		add_action(
			'admin_notices',
			static function () use ($type, $message_full) {
				echo '<div class="notice is-dismissible ' . esc_attr($type) . '" style="padding:12px 12px"> <p>
					' . wp_kses_post($message_full) . '
				</p></div>';
			}
		);

	}

	private static function admin_notice(Notice_Types $type, string $message)
	{
		$message_full   = '<strong>Allergens and Dietary: </strong> '. $message;
		$html = '<div class="notice is-dismissible ' . esc_attr($type) . '"> <p>
			' . wp_kses_post($message_full) . '
		</p></div>';
		echo $html;

	}

	public function display_admin_notice(Notice_Types $type, string $message){
		add_action('admin_notices', self::admin_notice($type, $message),5);
		// add_action('admin_notices',  static function() use ($type, $message) {
		// 	self::admin_notice($type, $message);
		// });
	}

}
