<?php

if (! defined('ABSPATH')) {
	exit;
}

if (! enum_exists('Notice_Types')) {
	require_once ALLERGENS_DIETARY_PRO_DIRNAME . '/php/notice/notice_Types.php';
}

if (! class_exists('Allergens_Dietary_Notices')){
	require_once ALLERGENS_DIETARY_FREE_DIRNAME . '/php/notice/notice.php';
}

/**
 * @brief This class handles the errors. 
 * and carries out potential error logs for future development
 * @author Verdi-B
 * @since 1.0.0
 * @date 4-11-2024
 */

class Allergens_Dietary_Pro_Notices extends Allergens_Dietary_Notices
{	
	protected function __construct() {}
	/**
	 * @brief method that handles error notices of this plugin. Every error notice generated by this plugin will call this function, sending both the notice type(WP css class) and the(translated) message
	 * @param Notice_Types $type
	 * @param string $message
	 * @return void
	 * @author Verdi-B
	 * @since 1.0.0
	 * @date 4-11-2024
	 */
	public function error_notice($type, $message)
	{
		$message_header = sprintf(__('%1$sAllergens and Dietary is inactive:%2$s', 'allergens-dietary'), '<p><strong>', '</strong></p>');
		$message_full   = $message_header . $message;
		add_action(
			'admin_notices',
			static function () use ($type, $message_full) {
				echo '<div class="notice ' . esc_attr($type) . '" style="padding:12px 12px"> <p>
					' . wp_kses_post($message_full) . '
				</p></div>';
			}
		);

	}
}
